/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
  
 import express from "express";
  import fs from "fs";
  import path from "path";
  const app = express();

  app.use(express.json());

  app.listen(3000, () => {
    console.log("Server is running on port 3000");
  })

  const PATH = path.join(process.cwd(), "todos.json");

  const readTodos = () => JSON.parse(fs.readFileSync(PATH, "utf-8"));
  const writeTodos = (todos) => fs.writeFileSync(PATH, JSON.stringify(todos, null, 2));

  app.get("/todos", (req, res) => {
    res.status(200).json(readTodos());
  })

  app.get("/todos/:id", (req, res) => {
    const id = Number(req.params.id);
    const todos = readTodos();
    const todo = todos.find(t => t.id === id);
    if(!todo) {
      return res.status(404).json({
        error: "Not found"
      })
    }
    res.status(200).json(todo);
  })

  app.post("/todos", (req, res) => {
    const {title, description, completed} = req.body;
    const todo = {
      id : Date.now(), // unique id based on timestamp, you can use any other method to generate unique ids
      title, 
      description,
      completed
    } 
    const todos = readTodos();
    todos.push(todo);
    writeTodos(todos);
    res.status(201).json({
      id: todo.id,
    })
  })

  app.put("/todos/:id", (req, res) => {
    const todos = readTodos();
    const id = Number (req.params.id);
    const index = todos.findIndex(t => t.id === id);
    if(index === -1) {
      return res.status(404).json({
        error: "Not found"
      })
      
    }
    
    todos[index] = {
        ...todos[index],
        ...req.body
        
      }
      writeTodos(todos);
      return res.status(200).json(todos[index]);
    }
  )

  app.delete("/todos/:id", (req, res) => {
     const todos = readTodos();

    const id = Number(req.params.id);
    const index = todos.findIndex(t => t.id === id);
    if(index === -1) {
      return res.status(404).json({
        error: "Not found"
      })
    }
   
    todos.splice(index, 1);
    writeTodos(todos);
    return res.status(200).json({
      success: true

  })
  })

  app.use((req, res) => {
  res.status(404).json({ error: "Route not found" });
});


  
  
  
  
  export default app;